"""empty message

Revision ID: 00001
Revises: None
Create Date: 2023-07-08 19:11:38.059646

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by almebic
revision = '00001'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requests_received',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gid', sa.CHAR(length=50), nullable=True),
    sa.Column('request', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('response', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requests_received_gid'), 'requests_received', ['gid'], unique=True)
    op.create_index(op.f('ix_requests_received_id'), 'requests_received', ['id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_requests_received_id'), table_name='requests_received')
    op.drop_index(op.f('ix_requests_received_gid'), table_name='requests_received')
    op.drop_table('requests_received')
    # ### end Alembic commands ###
